### ISSUE TITLE
[runwhen-local-feedback] Swap position of explanation and command & format fix

### ISSUE THREAD

**Issue by jon-funk** [runwhen-contrib/runwhen-local#221]
**Observation** 
- Proposed by user to swap position of explanation and command for better readability - as users will want to understand the command before running it
- Fix formatting of `CommandWhat` in the search:
![image (3)](https://github.com/runwhen-contrib/runwhen-local/assets/28266570/b8108c8a-01c5-47ed-bfaa-6d74a74e393c)

**Possible Suggestions**

**Any other details or context**

**Comment by stewartshea** [comment]
I think this has been completed with some of the previous layout changes. If not, please feel free to re-open.
