### ISSUE TITLE
Listing PVCs in terminating State

### ISSUE THREAD

**Issue by zohebk8s** [runwhen-contrib/runwhen-local#226]
Hi Team,

Environment is Azure AKS 1.25.6

I’ve deployed runwhen-local and able to access dashboard.

I just deleted a PVC. To validate the command/info available in runwhen-local dashboard. The expected result is, it should list the PVC as the PVC is in terminating state. It didn’t happen.

**Comment by stewartshea** [comment]
Thanks for reporting, can you provide any before and after command output? 

I will replicate as well, I just want to make sure I'm following your exact sequence so that we can improve the command. 

thanks so much!

**Comment by zohebk8s** [comment]
shaik [ ~/.kube ]$ kubectl get pvc -A
NAMESPACE   NAME                         STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
keycloak    data-keycloak-postgresql-0   Terminating   pvc-b4a319a7-9303-42d1-937a-9e2922758c3c   8Gi        RWO            default        3h16m
shaik [ ~/.kube ]$ for pvc in $(kubectl get pvc -n keycloak --context zoh-runwhen -o json | jq -r '.items[] | select(.status.phase != "Bound") | .metadata.name'); do kubectl get events -n keycloak --context zoh-runwhen --field-selector involvedObject.name=$pvc -o json | jq '.items[]| "Last Timestamp: " + .lastTimestamp + " Name: " + .involvedObject.name + " Message: " + .message'; done
shaik [ ~/.kube ]$ kubectl get pvc -A
NAMESPACE   NAME                         STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
keycloak    data-keycloak-postgresql-0   Terminating   pvc-b4a319a7-9303-42d1-937a-9e2922758c3c   8Gi        RWO            default        3h22m
shaik [ ~/.kube ]$ for pvc in $(kubectl get pvc -n keycloak --context zoh-runwhen -o json | jq -r '.items[] | select(.status.phase != "Bound") | .metadata.name'); do kubectl get events -n keycloak --context zoh-runwhen --field-selector involvedObject.name=$pvc -o json | jq '.items[]| "Last Timestamp: " + .lastTimestamp + " Name: " + .involvedObject.name + " Message: " + .message'; done
<img width="960" alt="image" src="https://github.com/runwhen-contrib/runwhen-local/assets/128701612/08a267b7-0715-40c9-b206-a5cd70c75819">

**Comment by stewartshea** [comment]
So this is really interesting; the command in question targets PersistentVolumes (not PersistentVolumeClaims) (example [here](https://runwhen-local.sandbox.runwhen.com/runwhen-local/runwhen-local-PVC-Healthcheck/#list-persistentvolumes-in-terminating-state)); 

I tested with a scenario in which a pod is still running attached to a pvc and then deleted the pvc... pvc cannot yet be removed until the pod dies. This would result in some output like this: 
```
# kubectl get pvc                                                                                    
NAME       STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-test   Terminating   pvc-55bd431d-d162-463e-bda0-b45d3f1032ae   1Gi        RWO            standard       4m6s
```

But, the PersistentVolume itself, supporting the PVC would still have a status of bound. So in that regard, the command is bringing about the right information (technically). Interestingly, if you inspect the PVC details, the status says nothing about "Terminating"... odd 
```
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pvc-test","namespace":"runwhen-local"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"standard"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
      volume.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
    creationTimestamp: "2023-07-20T15:51:37Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2023-07-20T15:52:26Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-test
    namespace: runwhen-local
    resourceVersion: "196994030"
    uid: 55bd431d-d162-463e-bda0-b45d3f1032ae
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-55bd431d-d162-463e-bda0-b45d3f1032ae
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
```
The status here says nothing about terminating, but we do have a deletion annotation that we could work with. 

What we might need here is an additional command to check for PVC's stuck in a terminating state (one level above the PV, since the PV hasn't gotten the instruction to be removed) - that seems pretty straight forward. Or a more advanced command that checks through the PV and the PVC (a little harder/more complex).

**Comment by zohebk8s** [comment]
Command to check for PVCs in terminating state might be helpful I believe.

**Comment by stewartshea** [comment]
Sounds good, I'll get that added in and let you know when it's done :)

**Comment by zohebk8s** [comment]
While doing POCs or testing, multiple times we have to deploy/test/delete/redeploy statefulsets. In this journey, a common issue is PVCs in terminating state.😊

**Comment by stewartshea** [comment]
@zohebk8s Let me know if this is trending in the direction of being useful. It's interesting since a PVC in my test (where I delete the PVC that is still attached to a running pod), won't actually have status.phase set to "Terminating", it's still "Bound" - but the CLI dhows Terminating likely due to the deletionTimestamp annotation which we use in the command. 

I wonder if this is specific to this type of scenario and if other scenarios might require additional tuning. 

Sample output: 
```
pvc-test is in Terminating state (Deletion started at: 2023-07-21T18:26:29Z). Finalizers: ["kubernetes.io/pvc-protection"]
```

Sample command from our runwhen-local sandbox: https://runwhen-local.sandbox.runwhen.com/failed/failed-PVC-Healthcheck/#list-persistentvolumeclaims-in-terminating-state

**Comment by zohebk8s** [comment]
@stewartshea Amazing and thank you. To test this, I deleted one PVC and tried again with the above command and it worked like a charm.

shaik [ ~ ]$ kubectl get pvc -n kubescape

NAME       STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kubevuln   Bound         pvc-8f1dc240-caec-4d16-97e0-4bf1bab44ee2   2Gi        RWO            default        28h
storage    Terminating   pvc-24e53d52-0664-4876-b06a-4c48aeb83fb1   5Gi        RWO            default        28h

shaik [ ~ ]$ kubectl get pvc -n kubescape -o json | jq -r '.items[] | select(.metadata.deletionTimestamp != null) | .metadata.name as $name | .metadata.deletionTimestamp as $deletion_time | .metadata.finalizers as $finalizers | "\($name) is in Terminating state (Deletion started at: \($deletion_time)). Finalizers: \($finalizers)"'

storage is in Terminating state (Deletion started at: 2023-07-21T19:25:16Z). Finalizers: ["kubernetes.io/pvc-protection"]

**Comment by zohebk8s** [comment]
@stewartshea Added more information specific to PVC Termination. Hope it will be of help.

shaik [ ~ ]$ kubectl get pvc storage -n kubescape -o yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: kubescape
    meta.helm.sh/release-namespace: kubescape
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
    volume.kubernetes.io/selected-node: aks-agentpool-26644758-vmss000000
    volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
  creationTimestamp: "2023-07-20T14:57:17Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-07-21T19:25:16Z"
  finalizers:
  - kubernetes.io/pvc-protection

The purpose of the Storage Object in Use Protection feature is to ensure that PersistentVolumeClaims (PVCs) in active use by a Pod and PersistentVolume (PVs) that are bound to PVCs are not removed from the system, as this may result in data loss.

shaik [ ~ ]$ kubectl get deploy -n kubescape | grep -i storage

storage          1/1     1            1           28h

shaik [ ~ ]$ kubectl get pvc -n kubescape | grep -i storage

NAME       STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
storage    Terminating   pvc-24e53d52-0664-4876-b06a-4c48aeb83fb1   5Gi        RWO            default        28h

shaik [ ~ ]$ kubectl scale deploy storage --replicas=0 -n kubescape

deployment.apps/storage scaled

shaik [ ~ ]$ kubectl get pods -n kubescape

storage-578ff8777d-7jfzk             1/1     Terminating   0             129m

shaik [ ~ ]$ kubectl get pods -n kubescape | grep -i storage --> As soon as the storage pod is scaled down, the terminating PVC is gone.


shaik [ ~ ]$ kubectl get pvc -n kubescape

NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kubevuln   Bound    pvc-8f1dc240-caec-4d16-97e0-4bf1bab44ee2   2Gi        RWO            default        28h

**Comment by stewartshea** [comment]
Perfect, would you say this new command resolves the issue?

**Comment by zohebk8s** [comment]
Yes the command provided by you is listing the PVCs which are in terminating state. Thank you for this.

**Comment by stewartshea** [comment]
Thanks for using the tool and providing the feedback. Growing a community like this starts small and your participation is greatly appreciated!

**Comment by zohebk8s** [comment]
@stewartshea Just now I've posted on Medium as well about the PVC termination use case.

Whenever you find time, please have a look.

https://medium.com/@zohebshaik7/kubernetes-controllers-5bfec6796a6a

**Comment by stewartshea** [comment]
Looks great @zohebk8s . 

If I can make one minor suggestion for formatting it would be that using code blocks to display any command line / terminal commands and output might be easier on the reader as opposed to screenshots or pasting the text with paragraph formatting.

**Comment by zohebk8s** [comment]
@stewartshea Noted with thanks.

I will take care of formatting going forward. Thanks for taking your time to go through the post 👍🏻
