### ISSUE TITLE
[runwhen-local-feedback] Enhancement Suggestion - add requests / resources to deployment example

### ISSUE THREAD

**Issue by zohebk8s** [runwhen-contrib/runwhen-local#233]
**Observation** 
Currently, RunWhen Local Deployment doesn't have resource requests/limits.

`root@zoh-aks:~# kubectl get pods --context=zoh-aks-cilium -n runwhen-local  --field-selector=status.phase=Running -ojson | jq -r '[.items[] as $pod | ($pod.spec.containers // [][])[] | select(.resources.requests == null) | {pod: $pod.metadata.name, container_without_requests: .name}]'
[
  {
    "pod": "runwhen-local-66bf8b7b78-jj2nm",
    "container_without_requests": "runwhen-local"
  }
]
`

**Possible Suggestions**

Use pod requests and limits to manage compute resources within a cluster. Pod requests and limits inform the Kubernetes scheduler of the compute resources to assign to a pod.

Pods in the BestEffort QoS class can use node resources that aren't specifically assigned to Pods in other QoS classes. For example, if you have a node with 16 CPU cores available to the kubelet, and you assign 4 CPU cores to a Guaranteed Pod, then a Pod in the BestEffort QoS class can try to use any amount of the remaining 12 CPU cores.

Adding below can help and it won't fail if we can clusters.

RunWhen Local Resource Management: 

request/limits - Pod Memory
request        - Pod CPU

**Any other details or context**

I've deployed RunWhen Local and scanned the cluster. As it doesn't have resource requests/limits defined, it has failed in compliance.

<img width="640" alt="image" src="https://github.com/runwhen-contrib/runwhen-local/assets/128701612/de5081e6-d3bd-440f-a84c-f1143db5f2b3">

**Comment by stewartshea** [comment]
Thanks for the suggestion @zohebk8s  - I can add these to the deployment manifest examples.

**Comment by zohebk8s** [comment]
Thank you for your response and acknowledgement.

**Comment by stewartshea** [comment]
@zohebk8s the PR auto-closed this. Let me know if the updated manifest resolves the issue - if not we can reopen.

**Comment by zohebk8s** [comment]
Amazing, thank you 👍🏻

you are faster than AI
