### ISSUE TITLE
[runwhen-local-feedback] Error 500 from Workspace Builder service for command "run": 'str' object does not support item assignment

### ISSUE THREAD

**Issue by pardubolloju** [runwhen-contrib/runwhen-local#241]
Hello RunWhen,
I was trying to test the runwhen in my local by referencing the [https://docs.runwhen.com/public/runwhen-local/getting-started/running-locally](url) when i execute this command 
    **shared $ docker exec -w /workspace-builder -- RunWhenLocal ./run.sh**
But i am encountering this error 
       **shared $ docker exec -w /workspace-builder -- RunWhenLocal ./run.sh                                                          
                       Error 500 from Workspace Builder service for command "run": 'str' object does not support item assignment**
Need help for this issue..
Thanks..

**Comment by stewartshea** [comment]
Hi @pardubolloju 

Can you please share any other details that you have after reading this document and collecting additional logs, and verifying that you have a valid `kubeconfig` and `workspaceInfo.yaml` file accessible to the container? 

https://docs.runwhen.com/public/runwhen-local/stuck-read-this.

Thanks!

**Comment by stewartshea** [comment]
@pardubolloju were you able to resolve the issue?

**Comment by stewartshea** [comment]
@pardubolloju were you able to resolve the issue?

**Comment by stewartshea** [comment]
Unfortunately without any additional details, we are going to close this ticket. Happy to re-open if/when needed.
