### ISSUE TITLE
[runwhen-local-feedback] authentication issues link is broken

### ISSUE THREAD

**Issue by emily-zall** [runwhen-contrib/runwhen-local#340]
**Observation** 
404 error on https://github.com/runwhen-contrib/runwhen-local/blob/main/docs/stuck-read-this.md#authentication-issues link found on https://docs.runwhen.com/public/v/runwhen-local/user-guide/user_guide-stuck_read_this

**Comment by stewartshea** [comment]
@emily-zall thanks for the issue! We recently moved a lot of the docs into a new gitbook space (and directly into the open source repo) which has a few broken links still. Thanks so much for raising this! 

The link should be updated now, it was supposed to easily link to the next heading. 

If you're having any other issues with your own authentication configuration, let us know and we can help out.

**Comment by stewartshea** [comment]
@emily-zall can you run the command with the `--verbose` switch 

e.g. 
```
docker exec -w /workspace-builder -- RunWhenLocal ./run.sh --verbose
```

Feel free to reach out to me on slack or discord as well if you prefer that route, or we can continue to troubleshoot here.
I wonder if there are file permission issues on the kubeconfig perhaps.... but hopefully the verbosity will shed some more details.

**Comment by stewartshea** [comment]
[This commit](https://github.com/runwhen-contrib/runwhen-local/commit/be30bf6fd03e9bfc0ad2f75d52312d7e6b09c44f) represents a rewrite of the gen_rw_kubeconfig.sh script to support multiple different user stanzas within the kubeconfig. It has, however, highlighted [this issue](https://github.com/runwhen-contrib/runwhen-local/issues/344) - so while the script should work well, the mentioned issue may be encountered.

**Comment by stewartshea** [comment]
Closed issue as we suspect the rewrite of the script has functioned properly.
