### ISSUE TITLE
Doc Bug Architecture.md

### ISSUE THREAD

**Issue by filiy** [runwhen-contrib/runwhen-local#424]
**Observation** 
The Architecture diagram in the architecture page looks a bit wonky in dark mode or when you expand the image
https://github.com/runwhen-contrib/runwhen-local/blob/main/docs/Architecture.md

![image](https://github.com/runwhen-contrib/runwhen-local/assets/24232206/ca060477-32cb-4f21-97bc-dcf3c03d23e2)

**Possible Suggestions**
Maybe give the image a white background instead of transparent?

**Comment by stewartshea** [comment]
Thanks for the issue, I'll definitely update it - it's also due for a slight update with our new cloudquery based indexer

**Comment by filiy** [comment]
Looks great on my end! Thanks!
