### ISSUE TITLE
Doc Bug Getting_Started-Running_Locally.md

### ISSUE THREAD

**Issue by filiy** [runwhen-contrib/runwhen-local#425]
**Observation** 

These two lines seem to contradict each other.

* https://github.com/runwhen-contrib/runwhen-local/blob/main/docs/Getting_Started-Running_Locally.md?plain=1#L70

"All keys with the value **placeholder** are required, but the value can be left as `placeholder` (they are only used when uploading content to the RunWhen platform for AI assisted troubleshooting)"

* https://github.com/runwhen-contrib/runwhen-local/blob/main/docs/Getting_Started-Running_Locally.md?plain=1#L159

"Everything in the workspaceInfo.yaml file that has a \[placeholder] beside it is not required for RunWhen Local to function . They are required when uploading configurations to the RunWhen Platform and are generated automatically when needed."

**Possible Suggestions**

Remove one of the lines?

**Comment by stewartshea** [comment]
Thanks for the issue, the documentation has been updated and addressed in this commit: https://github.com/runwhen-contrib/runwhen-local/commit/40a41f9764338eb7320e25e97db020b0af067755

**Comment by filiy** [comment]
Excellent!
