### ISSUE TITLE
Enhancement - Getting_Started-Running_Locally.md - SELinux

### ISSUE THREAD

**Issue by filiy** [runwhen-contrib/runwhen-local#426]
**Observation** 
If running podman on a Linux distro with SELinux enabled users may have a hard time running the pod and mounting the volume in.

**Possible Suggestions**

Adding "--security-opt label=disable" can get things going quickly so you don't get access denied errors when the pod tries to access the shared volume mount.

podman run --platform=linux/arm64 --name RunWhenLocal -p 8081:8081 -v $workdir/shared:/shared  --security-opt label=disable --userns=keep-id:uid=999,gid=999 ghcr.io/runwhen-contrib/runwhen-local:latest

**Comment by stewartshea** [comment]
Addressed in this commit: https://github.com/runwhen-contrib/runwhen-local/commit/40a41f9764338eb7320e25e97db020b0af067755

**Comment by filiy** [comment]
Looks great!
