### ISSUE TITLE
[runwhen-local-feedback]  cannot access local variable 'encoded_kubeconfig_file'

### ISSUE THREAD

**Issue by zacpez** [runwhen-contrib/runwhen-local#500]
**Observation** 
Unable to complete getting started guide here: https://docs.runwhen.com/public/v/runwhen-local/user-guide/installation/getting_started-running_locally

Encountered error
```
Error 500 from Workspace Builder service for command "run": cannot access local variable 'encoded_kubeconfig_file' where it is not associated with a value
```

I didn't deep dive into the code to provide more helpful insight. Let me know if there is anything additional you'd like me to try.

**Possible Suggestions**
Option 1 (workaround I was able to use):
Add the following to the example workspaceConfig.yaml in the documents to the qualified path is available.
```
    cloudConfig:
      kubernetes:
        kubeconfigFile: /shared/kubeconfig  
```
Option 2:
Update the config loader, so that the gen_rw_kubeconfig.sh generated kubeconfig written to the shared directory is loaded by default.
 
**Any other details or context**

**Comment by stewartshea** [comment]
Thanks for raising this, I think this is just an issue with the example in the documentation in that the workspaceInfo.yaml has taken on an updated form and what is in there is likely deprecated. 

Needs: 
- doc update with validation.

**Comment by stewartshea** [comment]
@zacpez Please let me know if the updated docs address the issue. From your comments, you indicated this might be an acceptable fix. It makes the most sense to keep it as a documentation fix rather than a code fix at this point.

**Comment by zacpez** [comment]
This works great, copied a new workspaceInfo.yaml to validate. I agree this is an appropriate path forward.
